openapi: 3.0.0
info:
  title: Rushikesh
  description: This is company doc made by me
  version: 1.0.0
  contact:
    email: rushi@gmail.com

servers:
  - url: http://localhost:4000
  - url: https://api.example.com

paths:
  /string:
    get:
      summary: Returns a string
      description: It just returns a string
      responses:
        "200":
          description: A string response
          content:
            text/plain:
              schema:
                type: string
